In [6]:
import numpy as np

In [2]:
np.zeros(1)

array([0.])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(1)

array([1.])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [7]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [9]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [10]:
np.eye(3, dtype = float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

#mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

In [20]:
##행렬식

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

arr.trace()

15

In [23]:
np.eye(3, dtype=int).trace()

3

In [28]:
arr_3 = np.array([[1,4,7,],[2,5,8],[3,6,9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [26]:
np.linalg.det(arr_2)

9.000000000000002

In [29]:
np.linalg.det(arr_3
             )

0.0

In [30]:
##역행렬

mat = np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [31]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [32]:
mat.dot(mat_inv)

array([[1., 0.],
       [0., 1.]])

In [33]:
## 고유값과 고유벡터

mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [34]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [36]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [37]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [38]:
mat.dot(eig_vec[:,0])

array([0., 1., 0.])

In [41]:
##lambda x

eig_val[0] * eig_vec[:,0]

array([0., 1., 0.])

In [42]:
A = np.random.randn(4,3,3)
print(A)

[[[-0.40647598  0.32574925 -1.21170637]
  [-1.03351115 -0.21362465 -1.05089714]
  [-0.12246952  0.36237325  0.1316939 ]]

 [[-0.6224371  -0.34186356 -1.70274429]
  [ 0.85197288 -0.00279441 -0.10996731]
  [ 0.37677356 -0.37366854  0.72600852]]

 [[-1.45579802  0.83055396  0.23368699]
  [-1.56378838 -0.03067709  0.48277672]
  [-0.92889709  0.69093848 -1.55725291]]

 [[ 0.75932829  0.19569844  0.30731729]
  [ 0.07394266 -0.57282122 -1.98833018]
  [-0.47753453 -0.3847933   0.87058797]]]


In [44]:
B = np.random.normal(loc = 1.56, scale = 0.67, size = (5,6))

print(B)

[[1.33202625 1.44035448 1.79131938 1.5160355  1.52998114 2.15349987]
 [1.35854244 1.75918719 1.80852671 0.56522431 2.68767885 1.81133546]
 [1.80342293 0.91938263 1.2281539  1.44869233 1.16578891 1.79980705]
 [1.48265957 1.17714349 1.48629806 1.84784379 0.91323353 1.89448429]
 [2.37785106 1.61336082 3.17340598 0.4643179  0.6761507  1.20895054]]


In [46]:
C = np.random.randint(10, 20, size = (3,4))

print(C)

[[12 11 12 12]
 [13 19 19 19]
 [10 15 11 17]]


In [47]:
A = [
   [10, 10, 10, 10, 10],
   [20, 20, 20, 20, 20],
   [30, 30, 30, 30, 30],
   [40, 40, 40, 40, 40],
   [50, 50, 50, 50, 50]
]

A = np.array(A)

A

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50]])

In [48]:
B = np.array([[13] * 5 for _ in range(5)]) 

B

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [60]:
C = np.array([13, 13, 13])
C

array([13, 13, 13])

In [61]:
result = A + C

result

ValueError: operands could not be broadcast together with shapes (5,5) (3,) 

In [54]:
result = A + 13

result

array([[23, 23, 23, 23, 23],
       [33, 33, 33, 33, 33],
       [43, 43, 43, 43, 43],
       [53, 53, 53, 53, 53],
       [63, 63, 63, 63, 63]])

In [56]:
B = np.array([1, 2, 3, 4, 5])
result2 = A + B
result2

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [71]:
a = np.array([[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]])
a

array([[151.4 , 172.45, 138.65, 177.63, 207.46],
       [ 44.64, 163.5 , 112.35,  73.55,  97.83]])

In [72]:
height = a[0,]
weight = a[1,]
height

array([151.4 , 172.45, 138.65, 177.63, 207.46])

In [73]:
weight

array([ 44.64, 163.5 , 112.35,  73.55,  97.83])

In [75]:
answer = np.where((height < 150) | (height > 195) | (weight >= 140)) ##위치 리턴
answer

(array([1, 2, 4], dtype=int64),)

In [7]:
arr_list = np.array([[[ -9, -14]], [[ 14 ,-2 ,0], [-14, -5, 1], [-11, 3, -6]], [[-2 ,-6], [18, 0]]])

arr_list

<ipython-input-7-e6d9d250794a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr_list = np.array([[[ -9, -14]], [[ 14 ,-2 ,0], [-14, -5, 1], [-11, 3, -6]], [[-2 ,-6], [18, 0]]])


array([list([[-9, -14]]), list([[14, -2, 0], [-14, -5, 1], [-11, 3, -6]]),
       list([[-2, -6], [18, 0]])], dtype=object)

In [20]:
for n in arr_list:
    print(len(n))
A = np.array([[0]])
print(type(A))


1
3
2
<class 'numpy.ndarray'>


In [9]:
for n in arr_list:
    n = np.array(n)
    print(n)

[[ -9 -14]]
[[ 14  -2   0]
 [-14  -5   1]
 [-11   3  -6]]
[[-2 -6]
 [18  0]]


In [33]:
a = np.array([[0]])

b = np.array([[ -9, -14]])
print(b.shape)
a = (a+1).dot(b*2)
a

(1, 2)


array([[-18, -28]])

In [35]:
A = np.array([[0]])
print(A)
for n in arr_list:
    n = np.array(n)
    if A.ndim == len(n):
        A = A.dot(n)
    else:
        A = (A+1).dot(n*2)
    print(A)

[[0]]
[[-18 -28]]


ValueError: shapes (1,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)