In [ ]:
%matplotlib inline

## What is PyTorch?
python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 한다.:
- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우. 

## Getting Started

tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능하다.

In [ ]:
from __future__ import print_function
import torch

torch.__version__

'1.12.1+cu113'

초기화 되지 않은 5x3 행렬 생성

In [ ]:
x = torch.empty(5,3)
print(x)

tensor([[8.4472e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


무작위로 초기화 된 행렬 생성

In [ ]:
x = torch.randn(5,3)
print(x)

x = torch.rand(5,3)
print(x)

tensor([[-0.1177, -0.0744, -0.8682],
        [-1.2876,  1.5999, -0.1976],
        [ 0.4303, -1.3419,  0.1220],
        [-1.3445,  0.6327, -0.3568],
        [ 0.0291, -1.0320,  0.5286]])
tensor([[0.6371, 0.2361, 0.1910],
        [0.5723, 0.8389, 0.9243],
        [0.5389, 0.6901, 0.9777],
        [0.3315, 0.3077, 0.2626],
        [0.4068, 0.1487, 0.5437]])


dtype이 long이고 0으로 채워진 행렬 생성

In [ ]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로 부터 tensor를 직접 생성

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만든다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예, dtype)를 재사용한다.

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)  # override dtype!
print(x)                                    # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7606, -2.6408, -0.4516],
        [-0.0837,  1.4243, -0.4723],
        [-0.3101, -0.0658, -0.0149],
        [ 1.9621, -1.6557, -0.4490],
        [ 1.2055, -1.4121, -1.1780]])


행렬의 크기 구하기

In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


덧셈 : 문법1

In [ ]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.7606, -2.6408, -0.4516],
        [-0.0837,  1.4243, -0.4723],
        [-0.3101, -0.0658, -0.0149],
        [ 1.9621, -1.6557, -0.4490],
        [ 1.2055, -1.4121, -1.1780]])
tensor([[0.1065, 0.1293, 0.5893],
        [0.5779, 0.3454, 0.4529],
        [0.6527, 0.5052, 0.0562],
        [0.4371, 0.6941, 0.0718],
        [0.4961, 0.2165, 0.0087]])
tensor([[ 0.8671, -2.5114,  0.1376],
        [ 0.4942,  1.7697, -0.0194],
        [ 0.3427,  0.4394,  0.0413],
        [ 2.3992, -0.9617, -0.3772],
        [ 1.7016, -1.1957, -1.1693]])


덧셈 : 문법2

In [ ]:
print(torch.add(x, y))

tensor([[ 0.8671, -2.5114,  0.1376],
        [ 0.4942,  1.7697, -0.0194],
        [ 0.3427,  0.4394,  0.0413],
        [ 2.3992, -0.9617, -0.3772],
        [ 1.7016, -1.1957, -1.1693]])


덧셈 : 결과 tensor를 인자로 제공

In [ ]:
result = torch.empty(5,3)
print(result)

torch.add(x, y, out = result)
print(result)

tensor([[ 8.4494e-35,  0.0000e+00,  4.4842e-44],
        [ 0.0000e+00,         nan,  1.6255e-43],
        [ 1.0948e+21,  9.2868e-04,  1.3556e-19],
        [ 9.8864e-33,  1.0008e+01,  5.5095e+11],
        [ 7.6510e-39,  0.0000e+00, -1.1693e+00]])
tensor([[ 0.8671, -2.5114,  0.1376],
        [ 0.4942,  1.7697, -0.0194],
        [ 0.3427,  0.4394,  0.0413],
        [ 2.3992, -0.9617, -0.3772],
        [ 1.7016, -1.1957, -1.1693]])


덧셈 : 바꿔치기 (In-place) 방식

In [ ]:
# adds x to y

print(y)
y.add_(x)
print(y)

tensor([[0.1065, 0.1293, 0.5893],
        [0.5779, 0.3454, 0.4529],
        [0.6527, 0.5052, 0.0562],
        [0.4371, 0.6941, 0.0718],
        [0.4961, 0.2165, 0.0087]])
tensor([[ 0.8671, -2.5114,  0.1376],
        [ 0.4942,  1.7697, -0.0194],
        [ 0.3427,  0.4394,  0.0413],
        [ 2.3992, -0.9617, -0.3772],
        [ 1.7016, -1.1957, -1.1693]])


Note
바꿔치기(In-place)방식으로 tensor의 값을 변경하는 연산은 _를 접미사로 갖는다.
예 : x.copy_(y), x.t_()는 x를 변경
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있다.

In [ ]:
print(x)
print(x[:,1])

tensor([[ 0.7606, -2.6408, -0.4516],
        [-0.0837,  1.4243, -0.4723],
        [-0.3101, -0.0658, -0.0149],
        [ 1.9621, -1.6557, -0.4490],
        [ 1.2055, -1.4121, -1.1780]])
tensor([-2.6408,  1.4243, -0.0658, -1.6557, -1.4121])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용

In [ ]:
import torch

x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1,2) # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 0.8279,  2.3514, -0.3649, -0.9402],
        [-0.0713, -1.1328,  1.1920,  0.5220],
        [ 0.1158,  0.5057, -0.3647,  1.0930],
        [-0.3609, -0.7821, -0.1155,  1.2848]])
tensor([ 0.8279,  2.3514, -0.3649, -0.9402, -0.0713, -1.1328,  1.1920,  0.5220,
         0.1158,  0.5057, -0.3647,  1.0930, -0.3609, -0.7821, -0.1155,  1.2848])
tensor([[ 0.8279,  2.3514],
        [-0.3649, -0.9402],
        [-0.0713, -1.1328],
        [ 1.1920,  0.5220],
        [ 0.1158,  0.5057],
        [-0.3647,  1.0930],
        [-0.3609, -0.7821],
        [-0.1155,  1.2848]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, `.item()`을 사용하면 숫자값을 얻을 수 있다.

In [ ]:
x = torch.randn(1)
print(x)

print(type(x), type(x.item()))
print(x.item())

tensor([-1.7275])
<class 'torch.Tensor'> <class 'float'>
-1.72751784324646


**읽을 거리**
전치(transposiong), 인덱싱(indexing), 슬라이싱(slising), 수학계산, 선형대수, 난수(random number) 등과 같은 100가지 이상의 Tensor연산은 <http://pytorch.org/docs/torch>에 설명되어있다.

## NumPy 변환(Bridge)
Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽다.
(CPU 상의)Torch Tensor와 NumPy배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 벼경된다.
- Torch Tensor를 NumPy 배열로 변환하기

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


Numpy 배열의 값이 어떻게 변하는지 확인


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


- NumPy 배열을 Torch Tensor로 변환하기

NumPy(np) 배열을 변경하면 Troch Tensor의 값도 자동 변경되는 것을 확인 할 수 있다.

In [ ]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의)반대 변환도 지원

## CUDA Tensors
`.to`메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다

In [ ]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행한다.
# ``torch.device``를 사용하여 tensor를 GPU 안 팎으로 이동하기

x = torch.rand(4,4)
if torch.cuda.is_available():
  device = "cuda:0" # torch.device("cuda:0")   # CUDA 장치 객치 (device object)로
  y = torch.ones_like(x, device = device) # GPU 상에 직접적으로 tensor를 생성하거나
  print(y)

  x = x.to(device)                        # ``.to("cuda")``를 사용하면 된다.
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))        # ``.to``는 dtype도 함께 변경한다.!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.0394, 1.2554, 1.7072, 1.9231],
        [1.3219, 1.2982, 1.1669, 1.2017],
        [1.9653, 1.1951, 1.9332, 1.3154],
        [1.0173, 1.1453, 1.0042, 1.5964]], device='cuda:0')
tensor([[1.0394, 1.2554, 1.7072, 1.9231],
        [1.3219, 1.2982, 1.1669, 1.2017],
        [1.9653, 1.1951, 1.9332, 1.3154],
        [1.0173, 1.1453, 1.0042, 1.5964]], dtype=torch.float64)


In [ ]:
x = x.cuda()